name: First Workflow

on:
 push:
   branches:
    - master


jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - run: echo 'Build stage'
 test:
  needs: build
  runs-on: windows-latest
  steps:
   - run: echo 'test stage'
   
  
